name: Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: "dev"
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up OpenTofu CLI
        uses: opentofu/setup-opentofu@v1

      - name: Initialize OpenTofu
        run: tofu init

      - name: Plan Deployment
        run: |
          tofu plan -var-file=./envs/dev.tfvars -out=plan.out
        env:
          TF_VAR_scaleway_access_key: ${{ secrets.TF_VAR_SCALEWAY_ACCESS_KEY }}
          TF_VAR_scaleway_secret_key: ${{ secrets.TF_VAR_SCALEWAY_SECRET_KEY }}
          TF_VAR_scaleway_organization_id: ${{ secrets.TF_VAR_SCALEWAY_ORGANIZATION_ID }}
          TF_VAR_scaleway_project_id: ${{ secrets.TF_VAR_SCALEWAY_PROJECT_ID }}
          TF_VAR_github_token: ${{ secrets.GH_ADMIN_TOKEN }}

      - name: Apply Plan
        run: |
          tofu apply -auto-approve plan.out
        env:
          TF_VAR_scaleway_access_key: ${{ secrets.TF_VAR_SCALEWAY_ACCESS_KEY }}
          TF_VAR_scaleway_secret_key: ${{ secrets.TF_VAR_SCALEWAY_SECRET_KEY }}
          TF_VAR_scaleway_organization_id: ${{ secrets.TF_VAR_SCALEWAY_ORGANIZATION_ID }}
          TF_VAR_scaleway_project_id: ${{ secrets.TF_VAR_SCALEWAY_PROJECT_ID }}
          TF_VAR_github_token: ${{ secrets.GH_ADMIN_TOKEN }}
